---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: fh-burgenland-sync-vcluster-kubectl
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: fh-burgenland-sync-vcluster-kubectl
      match:
        any:
          - resources:
              names:
                - "vc-*"
              kinds:
                - Secret
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - default
                - kube-public
                - kyverno
                - cilium
      context:
        - name: namespace
          variable:
            value: "{{ request.object.metadata.namespace }}"
        - name: name
          variable:
            value: "{{ request.object.metadata.name }}"
        - name: ca
          variable: 
            value: "{{ request.object.data.\"certificate-authority\" }}"
        - name: cert
          variable: 
            value: "{{ request.object.data.\"client-certificate\" }}"
        - name: key
          variable: 
            value: "{{ request.object.data.\"client-key\" }}"
        - name: vclusterName
          variable:
            value: "{{ namespace }}"
            jmesPath: 'to_string(@)'
      generate:
        kind: Secret
        apiVersion: v1
        name: "{{ vclusterName }}"
        namespace: fh-burgenland-argocd
        synchronize: true
        data:
          kind: Secret
          metadata:
            labels:
              argocd.argoproj.io/secret-type: cluster
          stringData:
            name: "{{ vclusterName }}"
            server: "https://{{ vclusterName }}.{{ namespace }}"
            config: |
              {
                "tlsClientConfig": {
                  "insecure": false,
                  "caData": "{{ ca }}",
                  "certData": "{{ cert }}",
                  "keyData": "{{ key }}"
                }
              }
